const $=s=>document.querySelector(s);
const icons={home:'<path d="m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18m-13 5 3 3 5-5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v7h5"/>',family:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4ZM17 4a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 5v2"/>',heart:'<path d="M20 5c-3-3-6-1-8 1-2-2-5-4-8-1-5 5 3 12 8 16 5-4 13-11 8-16Z"/>',meal:'<path d="M3 12h18c0 7-18 7-18 0Zm2 8h14M8 3v5m4-6v6m4-5v5"/>',care:'<path d="M4 13 12 5l8 8v8H4ZM9 21v-6h6v6M10 5V2h4v3"/>',medical:'<rect x="3" y="6" width="18" height="15" rx="2"/><path d="M8 6V3h8v3m-4 4v8m-4-4h8"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.heart}</svg>`;
const services=[{id:'medical',name:'陪伴就医',category:'医',hours:3,icon:'medical',desc:'协助就诊流程、陪同往返，让每一次出门多一份安心。',short:'有人同行，全程安心'},{id:'meal',name:'营养助餐',category:'食',hours:1,icon:'meal',desc:'预约日常送餐与用餐陪伴，把关心放进一日三餐。',short:'一日三餐，温暖如常'},{id:'care',name:'生活照料',category:'用',hours:2,icon:'care',desc:'居家整理、日常采买与生活协助，照顾熟悉的家。',short:'用心照料，安享日常'},{id:'walk',name:'安心助行',category:'行',hours:2,icon:'family',desc:'陪同散步与社区出行，在熟悉的风景中从容生活。'},{id:'chat',name:'暖心陪伴',category:'情',hours:1,icon:'heart',desc:'聊聊家常、读读书，让日常有倾听，也有回应。'},{id:'visit',name:'关怀探访',category:'情',hours:2,icon:'calendar',desc:'定期上门问候与生活状况记录，把近况带给远方家人。'}];
const tasks=[{id:'v1',name:'陪社区长者，走一段春风里的路',desc:'社区花园 · 陪伴散步 · 约 2 小时',hours:2},{id:'v2',name:'把一份热饭，送到长者家门口',desc:'邻里助餐站 · 送餐协助 · 约 1 小时',hours:1},{id:'v3',name:'坐下来，听一段关于从前的故事',desc:'社区活动室 · 阅读陪伴 · 约 2 小时',hours:2}];
function future(n){const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const key='shiguang-care-v1';const seed=()=>({balance:24,orders:[{id:'demo1',service:'medical',date:future(1),time:'09:00',place:'社区门诊（演示）',status:'已预约',hours:3},{id:'demo2',service:'meal',date:future(2),time:'12:00',place:'社区助餐站（演示）',status:'已预约',hours:1}],ledger:[{label:'初始体验时间',amount:28,date:future(0)},{label:'陪伴就医 · 示例预约',amount:-3,date:future(0)},{label:'营养助餐 · 示例预约',amount:-1,date:future(0)}],volunteers:{},messages:[],large:false});
let state;try{state=JSON.parse(localStorage.getItem(key));if(!state||!Number.isFinite(state.balance)||!Array.isArray(state.orders)||!Array.isArray(state.ledger)||!state.volunteers||!Array.isArray(state.messages))state=seed()}catch{state=seed()}
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{toast('浏览器无法保存，当前操作仅在本次页面有效。')}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000)}
const nav=[['home','home','首页概览'],['services','calendar','服务预约'],['wallet','clock','时间账户'],['family','family','家属关怀'],['volunteer','heart','志愿服务']];
const pending=()=>state.orders.filter(o=>o.status==='已预约').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
const heading=(a,b)=>`<div class="page-heading"><h1>${a}</h1><p>${b}</p></div>`;
function schedule(){return pending().slice(0,3).map(o=>`<div class="schedule-row"><p>${esc(o.date)} · ${esc(o.time)}</p><strong>${services.find(s=>s.id===o.service)?.name||'服务预约'}</strong><p>${esc(o.place)}</p></div>`).join('')||'<p class="muted">还没有近期安排，预约一份关怀吧。</p>'}
function home(){return `<section class="hero"><div class="hero-copy"><h1>让陪伴，<br>跨越山海。</h1><p>把今天的善意，存成明天的温暖。</p><div class="actions"><button class="primary" data-route="services">预约一份关怀 <span>↗</span></button><button class="secondary" data-route="volunteer">存入我的时间 <span>↗</span></button></div><p class="signature">时光里 · 有你 · 更美好</p></div><img class="hero-image" src="./assets/companionship.png" alt="长者与家人在花园中相伴微笑，AI生成情境图片"></section><section class="stats" aria-label="演示账户概览"><div class="stat">${icon('clock')}<div><p>时间余额</p><strong>${state.balance}<small>小时</small></strong><p class="caption">每一份时间，都是爱的储蓄</p></div></div><div class="stat">${icon('calendar')}<div><p>待办服务</p><strong>${pending().length}<small>项</small></strong><p class="caption">用行动，让关怀不再等待</p></div></div><div class="stat">${icon('family')}<div><p>关怀对象</p><strong>1<small>位</small></strong><p class="caption">家有一老，心中有暖</p></div></div></section><div class="home-bottom"><section class="panel"><div class="section-head"><h2>生活里的每一份关怀</h2><span>温暖的陪伴 · 更好的晚年</span></div><div class="service-grid">${services.slice(0,3).map(s=>`<button class="service-tile" data-book="${s.id}">${icon(s.icon)}<h3>${s.name}</h3><p>${s.short}</p><div class="tile-link">了解与预约 <span>↗</span></div></button>`).join('')}</div></section><section class="panel"><div class="section-head"><h3>近期安排</h3><button class="text-button" data-route="services">查看全部</button></div><div class="schedule">${schedule()}</div><p class="quote">平凡的日子里，藏着最珍贵的时光。</p></section></div>`}
let category='全部',query='';
function orderTable(){return `<div class="table-wrap"><table><thead><tr><th>服务项目</th><th>日期 / 时间</th><th>服务地点</th><th>时间</th><th>状态 / 操作</th></tr></thead><tbody>${state.orders.map(o=>`<tr><td>${services.find(s=>s.id===o.service)?.name||'服务'}</td><td>${esc(o.date)} ${esc(o.time)}</td><td>${esc(o.place)}</td><td>${o.hours} 小时</td><td>${o.status}${o.status==='已预约'?` · <button class="text-button" data-cancel="${o.id}">取消</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
function catalog(){const list=services.filter(s=>(category==='全部'||s.category===category)&&s.name.includes(query));return list.length?list.map(s=>`<article>${icon(s.icon)}<h3>${s.name}</h3><p>${s.desc}</p><div class="price">${s.hours} <small>小时 / 次</small></div><button class="primary" data-book="${s.id}">预约这份关怀 <span>↗</span></button></article>`).join(''):'<p class="empty">没有找到服务，试试其他关键词。</p>'}
function servicePage(){return heading('把关怀，安排在日常。','围绕医、食、行、情、用，找到适合家人的照护。')+`<div class="toolbar"><div class="filters">${['全部','医','食','行','情','用'].map(c=>`<button class="filter ${category===c?'active':''}" data-filter="${c}">${c==='全部'?'全部服务':c}</button>`).join('')}</div><input class="search" aria-label="搜索服务" placeholder="搜索服务名称" value="${esc(query)}"></div><section class="catalog" id="catalog">${catalog()}</section><h2 class="subheading">我的预约</h2>${orderTable()}<p class="notice">服务时长为体验规则，不代表实际报价；取消预约会将时间退回账户。</p>`}
function wallet(){return heading('让时间，成为爱的积蓄。','提供一份陪伴，存下一份温暖；需要时，为家人兑换照护。')+`<section class="balance-panel"><div><span>可用时间 · 演示账户</span><h2>${state.balance} <small>小时</small></h2><p>时间是互助的记录，也是人与人之间的联结。</p></div><button class="secondary" data-route="volunteer">参与志愿服务，存入时间 ↗</button></section><div class="section-head subheading"><h2>时间收支明细</h2><button class="text-button" id="export">导出记录</button></div><div class="table-wrap"><table><thead><tr><th>时间</th><th>记录事项</th><th>变动（小时）</th></tr></thead><tbody>${[...state.ledger].reverse().map(l=>`<tr><td>${esc(l.date)}</td><td>${esc(l.label)}</td><td>${l.amount>0?'+':''}${l.amount}</td></tr>`).join('')}</tbody></table></div><p class="notice">项目材料提出时间互助模式。本演示使用小时记账，不提供货币购买、提现或真实结算。</p>`}
function family(){return heading('距离再远，牵挂始终在。','在这里，看见家人的日常，也留下你的关心。')+`<div class="family-layout"><section class="panel"><img class="portrait" src="./assets/companionship.png" alt="AI生成长者情境肖像"><h2>林阿姨</h2><p class="muted">关怀对象 · 演示人物</p><p>喜欢散步、养花和听老歌。<br>愿每一个平常的日子，都有人陪伴。</p><button class="primary" data-route="services">为她预约服务 ↗</button></section><section class="panel"><div class="section-head"><h2>日常关怀记录</h2><span>示例内容</span></div><div class="health-row"><span>生活起居</span><span>完成晨间散步</span></div><div class="health-row"><span>餐饮情况</span><span>已用午餐</span></div><div class="health-row"><span>用药提醒</span><span>尚未配置</span></div><div class="health-row"><span>健康与位置设备</span><span>未连接</span></div><p class="notice">这里展示照护记录的呈现方式，没有接入医疗数据、定位设备或紧急求助系统。</p></section></div><section class="panel subheading"><h2>给家人留一句话</h2><form id="message-form"><label for="message">把想说的话，写在这里（仅本机保存）</label><textarea id="message" required maxlength="300" placeholder="等下次回家，我们一起去看看花。"></textarea><button class="primary" style="margin-top:14px">保存关怀留言</button></form><div id="messages">${state.messages.map(m=>`<div class="health-row"><span>${esc(m.text)}</span><small>${esc(m.date)}</small></div>`).join('')}</div></section>`}
function volunteer(){return heading('把你的时间，变成温暖。','从一件力所能及的小事开始，成为邻里之间的那份依靠。')+`<p class="notice">以下为模拟任务。报名后可体验完成服务与时间入账，不会形成真实志愿派单。</p><section>${tasks.map(t=>`<article class="volunteer-row"><div><h3>${t.name}</h3><p>${t.desc}</p><span class="status">可存入 ${t.hours} 小时${state.volunteers[t.id]==='done'?' · 已完成并入账':''}</span></div>${state.volunteers[t.id]==='done'?'<span>感谢你的温暖付出</span>':`<button class="${state.volunteers[t.id]?'secondary':'primary'}" data-vol="${t.id}">${state.volunteers[t.id]?'完成服务（演示）':'报名参与'}</button>`}</article>`).join('')}</section><section class="panel subheading"><h2>让每一份善意，都有回响。</h2><p>报名参与 → 完成陪伴 → 存入时间 → 兑换关怀</p><p class="notice">实际服务应由运营方完成身份核验、能力审核、服务确认和质量回访；本地演示不替代这些流程。</p></section>`}
function render(){let route=location.hash.slice(1)||'home';if(!nav.some(n=>n[0]===route))route='home';$('#nav').innerHTML=nav.map(([id,i,label])=>`<a href="#${id}" class="${id===route?'active':''}" ${id===route?'aria-current="page"':''}>${icon(i)}${label}</a>`).join('');$('#app').innerHTML=({home,services:servicePage,wallet,family,volunteer}[route])();document.body.classList.toggle('large',state.large);$('#large-text').setAttribute('aria-pressed',String(state.large));document.title=`${nav.find(n=>n[0]===route)[2]} · 时光养老`;}
let selected;function book(id){selected=services.find(s=>s.id===id);$('#booking-form').reset();$('#dialog-title').textContent=selected.name;$('#dialog-desc').textContent=`本次使用 ${selected.hours} 小时 · 可用时间 ${state.balance} 小时`;$('#form-error').textContent='';const d=$('[name=date]');d.min=future(0);d.value=future(1);$('#modal').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.route)location.hash=b.dataset.route;if(b.dataset.book)book(b.dataset.book);if(b.classList.contains('close'))$('#modal').close();if(b.dataset.filter){category=b.dataset.filter;render()}if(b.id==='large-text'){state.large=!state.large;save();render()}if(b.dataset.cancel){const o=state.orders.find(x=>x.id===b.dataset.cancel);if(o&&o.status==='已预约'){o.status='已取消';state.balance+=o.hours;state.ledger.push({label:`${services.find(s=>s.id===o.service).name} · 取消返还`,amount:o.hours,date:future(0)});save();render();toast('预约已取消，时间已退回。')}}if(b.dataset.vol){const t=tasks.find(x=>x.id===b.dataset.vol);if(!state.volunteers[t.id]){state.volunteers[t.id]='joined';toast('已保存模拟报名，可继续体验服务完成。')}else if(state.volunteers[t.id]==='joined'){state.volunteers[t.id]='done';state.balance+=t.hours;state.ledger.push({label:`志愿服务 · ${t.name}`,amount:t.hours,date:future(0)});toast(`感谢你的陪伴，${t.hours} 小时已存入。`)}save();render()}if(b.id==='export'){const blob=new Blob([JSON.stringify({说明:'时光养老本地演示记录',...state},null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='时光养老-时间记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}});
document.addEventListener('input',e=>{if(e.target.matches('.search')){query=e.target.value;$('#catalog').innerHTML=catalog()}});
$('#booking-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(state.balance<selected.hours){$('#form-error').textContent='可用时间不足，请先参与志愿服务积累时间。';return}if(f.get('date')<future(0)||!f.get('place').trim()){$('#form-error').textContent='请填写有效日期和服务地点。';return}state.balance-=selected.hours;state.orders.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),service:selected.id,date:f.get('date'),time:f.get('time'),place:f.get('place').trim(),note:f.get('note').trim(),hours:selected.hours,status:'已预约'});state.ledger.push({label:`${selected.name} · 预约扣除`,amount:-selected.hours,date:future(0)});save();$('#modal').close();render();toast('本地预约已保存，可在服务预约中查看。')});
document.addEventListener('submit',e=>{if(e.target.id==='message-form'){e.preventDefault();const text=$('#message').value.trim();if(!text)return;state.messages.unshift({text,date:future(0)});save();render();toast('留言已保存于本机，未发送给他人。')}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();
